#kubectl run -i --tty load-generator --image=busybox /bin/sh
#while true; do wget -q -O- http://frontend.prod.svc.cluster.local; done


apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: drupal
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: drupal
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 80
  - type: Resource
    resource:
      name: memory
      targetAverageValue: 100Mi
